(* use file

  Automatically generated by ocm.
  This file should not be mentioned in a system definition
  After compiling all files to bytecode, enter the following at the toplevel:

  #use "/home/rai/eaburns/src/scripts/use.ml";;

  (Need absolute path because there may be others in active directories.)
*)


#directory "/home/rai/eaburns/src/ocaml/structs/bytecode";;
#directory "/home/rai/eaburns/src/ocaml/structs";;
#directory "/home/rai/eaburns/src/ocaml/wrutils/bytecode";;
#directory "/home/rai/eaburns/src/ocaml/wrutils";;
#directory "/home/rai/eaburns/src/ocaml/math/bytecode";;
#directory "/home/rai/eaburns/src/ocaml/math";;
#directory "/home/rai/eaburns/src/ocaml/rdb/bytecode";;
#directory "/home/rai/eaburns/src/ocaml/rdb";;
#directory "/home/rai/eaburns/src/ocaml/ps_plot/bytecode";;
#directory "/home/rai/eaburns/src/ocaml/ps_plot";;
#directory "/home/rai/eaburns/src/scripts/bytecode";;
#directory "/home/rai/eaburns/src/scripts";;


#load "graph.cmo";;
#load "dag.cmo";;
#load "utils.cmo";;
#load "math.cmo";;
#load "dset.cmo";;
#load "fixedq.cmo";;
#load "wrchar.cmo";;
#load "eqvclass.cmo";;
#load "wrlist.cmo";;
#load "wrstr.cmo";;
#load "wrfname.cmo";;
#load "wrio.cmo";;
#load "wrarray.cmo";;
#load "dpq.cmo";;
#load "vector.cmo";;
#load "data.cmo";;
#load "verb.cmo";;
#load "rdb.cmo";;
#load "wrht.cmo";;
#load "wrstrm.cmo";;
#load "wrsys.cmo";;
#load "datafile.cmo";;
#load "namespace.cmo";;
#load "ps_plot_interface.cmo";;
#load "ps_plot.cmo";;
#load "plot_generator_deprecated.cmo";;
#load "plot_tiles.cmo";;
#load "uset.cmo";;
#load "dbl.cmo";;
#load "dblq.cmo";;
#load "cache.cmo";;
#load "ord_opt.cmo";;
#load "matrix.cmo";;
#load "functions.cmo";;
#load "probability.cmo";;
#load "stats.cmo";;
#load "dist_opt.cmo";;
#load "plot_grid.cmo";;
#load "dfutils.cmo";;
#load "plot_generator.cmo";;
#load "plot_macros.cmo";;
#load "udp.cmo";;
#load "upq.cmo";;
#load "doset.cmo";;
#load "geq.cmo";;
#load "scatter_plot.cmo";;
#load "duf.cmo";;
#load "backedht.cmo";;
#load "num_opt.cmo";;
#load "wrlexing.cmo";;
#load "wrformat.cmo";;
#load "latex.cmo";;
#load "convex_hull.cmo";;
#load "multiq.cmo";;
#load "dufi.cmo";;
#load "lq.cmo";;
#load "lst.cmo";;
#load "coatcheck.cmo";;
#load "pq.cmo";;
#load "wrrandom.cmo";;
#load "domain.cmo";;
#load "alg.cmo";;
#load "mmh.cmo";;
#load "logfn.cmo";;
#load "uf.cmo";;
#load "dlist.cmo";;


(* EOF *)
